export const COUNTRIES_DATA = [
  { code: 'AF', name: 'Afghanistan', currency: 'AFN', symbol: '؋', rate: 70.5, timezone: 'Asia/Kabul' },
  { code: 'AL', name: 'Albania', currency: 'ALL', symbol: 'L', rate: 93.4, timezone: 'Europe/Tirane' },
  { code: 'DZ', name: 'Algeria', currency: 'DZD', symbol: 'د.ج', rate: 134.2, timezone: 'Africa/Algiers' },
  { code: 'AD', name: 'Andorra', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Andorra' },
  { code: 'AO', name: 'Angola', currency: 'AOA', symbol: 'Kz', rate: 830.0, timezone: 'Africa/Luanda' },
  { code: 'AR', name: 'Argentina', currency: 'ARS', symbol: '$', rate: 900.0, timezone: 'America/Argentina/Buenos_Aires' },
  { code: 'AM', name: 'Armenia', currency: 'AMD', symbol: '֏', rate: 388.5, timezone: 'Asia/Yerevan' },
  { code: 'AU', name: 'Australia', currency: 'AUD', symbol: 'A$', rate: 1.51, timezone: 'Australia/Sydney' },
  { code: 'AT', name: 'Austria', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Vienna' },
  { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', symbol: '₼', rate: 1.70, timezone: 'Asia/Baku' },
  { code: 'BS', name: 'Bahamas', currency: 'BSD', symbol: 'B$', rate: 1.00, timezone: 'America/Nassau' },
  { code: 'BH', name: 'Bahrain', currency: 'BHD', symbol: '.د.ب', rate: 0.376, timezone: 'Asia/Bahrain' },
  { code: 'BD', name: 'Bangladesh', currency: 'BDT', symbol: '৳', rate: 117.0, timezone: 'Asia/Dhaka' },
  { code: 'BB', name: 'Barbados', currency: 'BBD', symbol: 'Bds$', rate: 2.00, timezone: 'America/Barbados' },
  { code: 'BY', name: 'Belarus', currency: 'BYN', symbol: 'Br', rate: 3.27, timezone: 'Europe/Minsk' },
  { code: 'BE', name: 'Belgium', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Brussels' },
  { code: 'BZ', name: 'Belize', currency: 'BZD', symbol: 'BZ$', rate: 2.00, timezone: 'America/Belize' },
  { code: 'BJ', name: 'Benin', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Porto-Novo' },
  { code: 'BM', name: 'Bermuda', currency: 'BMD', symbol: '$', rate: 1.00, timezone: 'Atlantic/Bermuda' },
  { code: 'BT', name: 'Bhutan', currency: 'BTN', symbol: 'Nu.', rate: 83.5, timezone: 'Asia/Thimphu' },
  { code: 'BO', name: 'Bolivia', currency: 'BOB', symbol: 'Bs.', rate: 6.91, timezone: 'America/La_Paz' },
  { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM', rate: 1.80, timezone: 'Europe/Sarajevo' },
  { code: 'BW', name: 'Botswana', currency: 'BWP', symbol: 'P', rate: 13.6, timezone: 'Africa/Gaborone' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', symbol: 'R$', rate: 5.25, timezone: 'America/Sao_Paulo' },
  { code: 'BN', name: 'Brunei', currency: 'BND', symbol: 'B$', rate: 1.35, timezone: 'Asia/Brunei' },
  { code: 'BG', name: 'Bulgaria', currency: 'BGN', symbol: 'лв', rate: 1.80, timezone: 'Europe/Sofia' },
  { code: 'BF', name: 'Burkina Faso', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Ouagadougou' },
  { code: 'BI', name: 'Burundi', currency: 'BIF', symbol: 'FBu', rate: 2870.0, timezone: 'Africa/Bujumbura' },
  { code: 'KH', name: 'Cambodia', currency: 'KHR', symbol: '៛', rate: 4095.0, timezone: 'Asia/Phnom_Penh' },
  { code: 'CM', name: 'Cameroon', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Douala' },
  { code: 'CA', name: 'Canada', currency: 'CAD', symbol: 'C$', rate: 1.37, timezone: 'America/Toronto' },
  { code: 'CV', name: 'Cape Verde', currency: 'CVE', symbol: 'Esc', rate: 101.4, timezone: 'Atlantic/Cape_Verde' },
  { code: 'CF', name: 'Central African Republic', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Bangui' },
  { code: 'TD', name: 'Chad', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Ndjamena' },
  { code: 'CL', name: 'Chile', currency: 'CLP', symbol: '$', rate: 910.0, timezone: 'America/Santiago' },
  { code: 'CN', name: 'China', currency: 'CNY', symbol: '¥', rate: 7.25, timezone: 'Asia/Shanghai' },
  { code: 'CO', name: 'Colombia', currency: 'COP', symbol: '$', rate: 3850.0, timezone: 'America/Bogota' },
  { code: 'KM', name: 'Comoros', currency: 'KMF', symbol: 'CF', rate: 452.5, timezone: 'Indian/Comoro' },
  { code: 'CG', name: 'Congo', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Brazzaville' },
  { code: 'CR', name: 'Costa Rica', currency: 'CRC', symbol: '₡', rate: 512.0, timezone: 'America/Costa_Rica' },
  { code: 'HR', name: 'Croatia', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Zagreb' },
  { code: 'CU', name: 'Cuba', currency: 'CUP', symbol: '$', rate: 24.0, timezone: 'America/Havana' },
  { code: 'CY', name: 'Cyprus', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Nicosia' },
  { code: 'CZ', name: 'Czechia', currency: 'CZK', symbol: 'Kč', rate: 22.8, timezone: 'Europe/Prague' },
  { code: 'DK', name: 'Denmark', currency: 'DKK', symbol: 'kr', rate: 6.87, timezone: 'Europe/Copenhagen' },
  { code: 'DJ', name: 'Djibouti', currency: 'DJF', symbol: 'Fdj', rate: 177.7, timezone: 'Africa/Djibouti' },
  { code: 'DM', name: 'Dominica', currency: 'XCD', symbol: '$', rate: 2.70, timezone: 'America/Dominica' },
  { code: 'DO', name: 'Dominican Republic', currency: 'DOP', symbol: 'RD$', rate: 59.2, timezone: 'America/Santo_Domingo' },
  { code: 'EC', name: 'Ecuador', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'America/Guayaquil' },
  { code: 'EG', name: 'Egypt', currency: 'EGP', symbol: 'E£', rate: 47.3, timezone: 'Africa/Cairo' },
  { code: 'SV', name: 'El Salvador', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'America/El_Salvador' },
  { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Malabo' },
  { code: 'ER', name: 'Eritrea', currency: 'ERN', symbol: 'Nfk', rate: 15.0, timezone: 'Africa/Asmara' },
  { code: 'EE', name: 'Estonia', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Tallinn' },
  { code: 'SZ', name: 'Eswatini', currency: 'SZL', symbol: 'L', rate: 18.5, timezone: 'Africa/Mbabane' },
  { code: 'ET', name: 'Ethiopia', currency: 'ETB', symbol: 'Br', rate: 57.2, timezone: 'Africa/Addis_Ababa' },
  { code: 'FJ', name: 'Fiji', currency: 'FJD', symbol: 'FJ$', rate: 2.24, timezone: 'Pacific/Fiji' },
  { code: 'FI', name: 'Finland', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Helsinki' },
  { code: 'FR', name: 'France', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Paris' },
  { code: 'GA', name: 'Gabon', currency: 'XAF', symbol: 'FCFA', rate: 603.5, timezone: 'Africa/Libreville' },
  { code: 'GM', name: 'Gambia', currency: 'GMD', symbol: 'D', rate: 68.0, timezone: 'Africa/Banjul' },
  { code: 'GE', name: 'Georgia', currency: 'GEL', symbol: '₾', rate: 2.72, timezone: 'Asia/Tbilisi' },
  { code: 'DE', name: 'Germany', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Berlin' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', symbol: 'GH₵', rate: 14.2, timezone: 'Africa/Accra' },
  { code: 'GR', name: 'Greece', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Athens' },
  { code: 'GD', name: 'Grenada', currency: 'XCD', symbol: '$', rate: 2.70, timezone: 'America/Grenada' },
  { code: 'GT', name: 'Guatemala', currency: 'GTQ', symbol: 'Q', rate: 7.78, timezone: 'America/Guatemala' },
  { code: 'GN', name: 'Guinea', currency: 'GNF', symbol: 'FG', rate: 8600.0, timezone: 'Africa/Conakry' },
  { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Bissau' },
  { code: 'GY', name: 'Guyana', currency: 'GYD', symbol: 'G$', rate: 209.0, timezone: 'America/Guyana' },
  { code: 'HT', name: 'Haiti', currency: 'HTG', symbol: 'G', rate: 132.5, timezone: 'America/Port-au-Prince' },
  { code: 'HN', name: 'Honduras', currency: 'HNL', symbol: 'L', rate: 24.7, timezone: 'America/Tegucigalpa' },
  { code: 'HU', name: 'Hungary', currency: 'HUF', symbol: 'Ft', rate: 358.0, timezone: 'Europe/Budapest' },
  { code: 'IS', name: 'Iceland', currency: 'ISK', symbol: 'kr', rate: 138.5, timezone: 'Atlantic/Reykjavik' },
  { code: 'IN', name: 'India', currency: 'INR', symbol: '₹', rate: 83.5, timezone: 'Asia/Kolkata' },
  { code: 'ID', name: 'Indonesia', currency: 'IDR', symbol: 'Rp', rate: 16250.0, timezone: 'Asia/Jakarta' },
  { code: 'IR', name: 'Iran', currency: 'IRR', symbol: '﷼', rate: 42000.0, timezone: 'Asia/Tehran' },
  { code: 'IQ', name: 'Iraq', currency: 'IQD', symbol: 'ع.د', rate: 1310.0, timezone: 'Asia/Baghdad' },
  { code: 'IE', name: 'Ireland', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Dublin' },
  { code: 'IL', name: 'Israel', currency: 'ILS', symbol: '₪', rate: 3.72, timezone: 'Asia/Jerusalem' },
  { code: 'IT', name: 'Italy', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Rome' },
  { code: 'JM', name: 'Jamaica', currency: 'JMD', symbol: 'J$', rate: 155.5, timezone: 'America/Kingston' },
  { code: 'JP', name: 'Japan', currency: 'JPY', symbol: '¥', rate: 156.4, timezone: 'Asia/Tokyo' },
  { code: 'JO', name: 'Jordan', currency: 'JOD', symbol: 'د.ا', rate: 0.709, timezone: 'Asia/Amman' },
  { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', symbol: '₸', rate: 445.0, timezone: 'Asia/Almaty' },
  { code: 'KE', name: 'Kenya', currency: 'KES', symbol: 'KSh', rate: 130.0, timezone: 'Africa/Nairobi' },
  { code: 'KI', name: 'Kiribati', currency: 'AUD', symbol: 'A$', rate: 1.51, timezone: 'Pacific/Tarawa' },
  { code: 'KP', name: 'Korea, North', currency: 'KPW', symbol: '₩', rate: 900.0, timezone: 'Asia/Pyongyang' },
  { code: 'KR', name: 'Korea, South', currency: 'KRW', symbol: '₩', rate: 1370.0, timezone: 'Asia/Seoul' },
  { code: 'KW', name: 'Kuwait', currency: 'KWD', symbol: 'د.ك', rate: 0.307, timezone: 'Asia/Kuwait' },
  { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', symbol: 'сом', rate: 88.0, timezone: 'Asia/Bishkek' },
  { code: 'LA', name: 'Laos', currency: 'LAK', symbol: '₭', rate: 21500.0, timezone: 'Asia/Vientiane' },
  { code: 'LV', name: 'Latvia', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Riga' },
  { code: 'LB', name: 'Lebanon', currency: 'LBP', symbol: 'ل.ل', rate: 89500.0, timezone: 'Asia/Beirut' },
  { code: 'LS', name: 'Lesotho', currency: 'LSL', symbol: 'L', rate: 18.5, timezone: 'Africa/Maseru' },
  { code: 'LR', name: 'Liberia', currency: 'LRD', symbol: 'L$', rate: 194.0, timezone: 'Africa/Monrovia' },
  { code: 'LY', name: 'Libya', currency: 'LYD', symbol: 'ل.د', rate: 4.85, timezone: 'Africa/Tripoli' },
  { code: 'LI', name: 'Liechtenstein', currency: 'CHF', symbol: 'CHF', rate: 0.91, timezone: 'Europe/Vaduz' },
  { code: 'LT', name: 'Lithuania', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Vilnius' },
  { code: 'LU', name: 'Luxembourg', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Luxembourg' },
  { code: 'MG', name: 'Madagascar', currency: 'MGA', symbol: 'Ar', rate: 4450.0, timezone: 'Indian/Antananarivo' },
  { code: 'MW', name: 'Malawi', currency: 'MWK', symbol: 'MK', rate: 1730.0, timezone: 'Africa/Lilongwe' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', symbol: 'RM', rate: 4.70, timezone: 'Asia/Kuala_Lumpur' },
  { code: 'MV', name: 'Maldives', currency: 'MVR', symbol: 'Rf', rate: 15.4, timezone: 'Indian/Maldives' },
  { code: 'ML', name: 'Mali', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Bamako' },
  { code: 'MT', name: 'Malta', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Malta' },
  { code: 'MH', name: 'Marshall Islands', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'Pacific/Majuro' },
  { code: 'MR', name: 'Mauritania', currency: 'MRU', symbol: 'UM', rate: 39.6, timezone: 'Africa/Nouakchott' },
  { code: 'MU', name: 'Mauritius', currency: 'MUR', symbol: '₨', rate: 46.2, timezone: 'Indian/Mauritius' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', symbol: '$', rate: 16.7, timezone: 'America/Mexico_City' },
  { code: 'FM', name: 'Micronesia', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'Pacific/Chuuk' },
  { code: 'MD', name: 'Moldova', currency: 'MDL', symbol: 'L', rate: 17.7, timezone: 'Europe/Chisinau' },
  { code: 'MC', name: 'Monaco', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Monaco' },
  { code: 'MN', name: 'Mongolia', currency: 'MNT', symbol: '₮', rate: 3380.0, timezone: 'Asia/Ulaanbaatar' },
  { code: 'ME', name: 'Montenegro', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Podgorica' },
  { code: 'MA', name: 'Morocco', currency: 'MAD', symbol: 'د.م.', rate: 10.0, timezone: 'Africa/Casablanca' },
  { code: 'MZ', name: 'Mozambique', currency: 'MZN', symbol: 'MT', rate: 63.8, timezone: 'Africa/Maputo' },
  { code: 'MM', name: 'Myanmar', currency: 'MMK', symbol: 'K', rate: 2100.0, timezone: 'Asia/Yangon' },
  { code: 'NA', name: 'Namibia', currency: 'NAD', symbol: 'N$', rate: 18.5, timezone: 'Africa/Windhoek' },
  { code: 'NR', name: 'Nauru', currency: 'AUD', symbol: 'A$', rate: 1.51, timezone: 'Pacific/Nauru' },
  { code: 'NP', name: 'Nepal', currency: 'NPR', symbol: '₨', rate: 133.5, timezone: 'Asia/Kathmandu' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Amsterdam' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', symbol: 'NZ$', rate: 1.63, timezone: 'Pacific/Auckland' },
  { code: 'NI', name: 'Nicaragua', currency: 'NIO', symbol: 'C$', rate: 36.7, timezone: 'America/Managua' },
  { code: 'NE', name: 'Niger', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Niamey' },
  { code: 'NG', name: 'Nigeria', currency: 'NGN', symbol: '₦', rate: 1500.0, timezone: 'Africa/Lagos' },
  { code: 'NO', name: 'Norway', currency: 'NOK', symbol: 'kr', rate: 10.6, timezone: 'Europe/Oslo' },
  { code: 'OM', name: 'Oman', currency: 'OMR', symbol: 'ر.ع.', rate: 0.385, timezone: 'Asia/Muscat' },
  { code: 'PK', name: 'Pakistan', currency: 'PKR', symbol: '₨', rate: 278.0, timezone: 'Asia/Karachi' },
  { code: 'PW', name: 'Palau', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'Pacific/Palau' },
  { code: 'PS', name: 'Palestine', currency: 'ILS', symbol: '₪', rate: 3.72, timezone: 'Asia/Gaza' },
  { code: 'PA', name: 'Panama', currency: 'PAB', symbol: 'B/.', rate: 1.00, timezone: 'America/Panama' },
  { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', symbol: 'K', rate: 3.88, timezone: 'Pacific/Port_Moresby' },
  { code: 'PY', name: 'Paraguay', currency: 'PYG', symbol: '₲', rate: 7450.0, timezone: 'America/Asuncion' },
  { code: 'PE', name: 'Peru', currency: 'PEN', symbol: 'S/.', rate: 3.73, timezone: 'America/Lima' },
  { code: 'PH', name: 'Philippines', currency: 'PHP', symbol: '₱', rate: 58.2, timezone: 'Asia/Manila' },
  { code: 'PL', name: 'Poland', currency: 'PLN', symbol: 'zł', rate: 3.95, timezone: 'Europe/Warsaw' },
  { code: 'PT', name: 'Portugal', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Lisbon' },
  { code: 'QA', name: 'Qatar', currency: 'QAR', symbol: 'ر.ق', rate: 3.64, timezone: 'Asia/Qatar' },
  { code: 'RO', name: 'Romania', currency: 'RON', symbol: 'lei', rate: 4.58, timezone: 'Europe/Bucharest' },
  { code: 'RU', name: 'Russia', currency: 'RUB', symbol: '₽', rate: 90.5, timezone: 'Europe/Moscow' },
  { code: 'RW', name: 'Rwanda', currency: 'RWF', symbol: 'FRw', rate: 1300.0, timezone: 'Africa/Kigali' },
  { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$', rate: 2.70, timezone: 'America/St_Kitts' },
  { code: 'LC', name: 'Saint Lucia', currency: 'XCD', symbol: '$', rate: 2.70, timezone: 'America/St_Lucia' },
  { code: 'VC', name: 'Saint Vincent', currency: 'XCD', symbol: '$', rate: 2.70, timezone: 'America/St_Vincent' },
  { code: 'WS', name: 'Samoa', currency: 'WST', symbol: 'SAT', rate: 2.75, timezone: 'Pacific/Apia' },
  { code: 'SM', name: 'San Marino', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/San_Marino' },
  { code: 'ST', name: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db', rate: 22.5, timezone: 'Africa/Sao_Tome' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', symbol: 'ر.س', rate: 3.75, timezone: 'Asia/Riyadh' },
  { code: 'SN', name: 'Senegal', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Dakar' },
  { code: 'RS', name: 'Serbia', currency: 'RSD', symbol: 'дин.', rate: 108.0, timezone: 'Europe/Belgrade' },
  { code: 'SC', name: 'Seychelles', currency: 'SCR', symbol: '₨', rate: 13.8, timezone: 'Indian/Mahe' },
  { code: 'SL', name: 'Sierra Leone', currency: 'SLE', symbol: 'Le', rate: 22.5, timezone: 'Africa/Freetown' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', symbol: 'S$', rate: 1.35, timezone: 'Asia/Singapore' },
  { code: 'SK', name: 'Slovakia', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Bratislava' },
  { code: 'SI', name: 'Slovenia', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Ljubljana' },
  { code: 'SB', name: 'Solomon Islands', currency: 'SBD', symbol: 'SI$', rate: 8.50, timezone: 'Pacific/Guadalcanal' },
  { code: 'SO', name: 'Somalia', currency: 'SOS', symbol: 'Sh.so.', rate: 570.0, timezone: 'Africa/Mogadishu' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', symbol: 'R', rate: 18.5, timezone: 'Africa/Johannesburg' },
  { code: 'SS', name: 'South Sudan', currency: 'SSP', symbol: 'SS$', rate: 130.0, timezone: 'Africa/Juba' },
  { code: 'ES', name: 'Spain', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Madrid' },
  { code: 'LK', name: 'Sri Lanka', currency: 'LKR', symbol: 'Rs', rate: 300.0, timezone: 'Asia/Colombo' },
  { code: 'SD', name: 'Sudan', currency: 'SDG', symbol: 'ج.س.', rate: 600.0, timezone: 'Africa/Khartoum' },
  { code: 'SR', name: 'Suriname', currency: 'SRD', symbol: '$', rate: 34.2, timezone: 'America/Paramaribo' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', symbol: 'kr', rate: 10.6, timezone: 'Europe/Stockholm' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', symbol: 'CHF', rate: 0.91, timezone: 'Europe/Zurich' },
  { code: 'SY', name: 'Syria', currency: 'SYP', symbol: '£S', rate: 13000.0, timezone: 'Asia/Damascus' },
  { code: 'TW', name: 'Taiwan', currency: 'TWD', symbol: 'NT$', rate: 32.3, timezone: 'Asia/Taipei' },
  { code: 'TJ', name: 'Tajikistan', currency: 'TJS', symbol: 'SM', rate: 10.9, timezone: 'Asia/Dushanbe' },
  { code: 'TZ', name: 'Tanzania', currency: 'TZS', symbol: 'TSh', rate: 2600.0, timezone: 'Africa/Dar_es_Salaam' },
  { code: 'TH', name: 'Thailand', currency: 'THB', symbol: '฿', rate: 36.6, timezone: 'Asia/Bangkok' },
  { code: 'TG', name: 'Togo', currency: 'XOF', symbol: 'CFA', rate: 603.5, timezone: 'Africa/Lome' },
  { code: 'TO', name: 'Tonga', currency: 'TOP', symbol: 'T$', rate: 2.36, timezone: 'Pacific/Tongatapu' },
  { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$', rate: 6.78, timezone: 'America/Port_of_Spain' },
  { code: 'TN', name: 'Tunisia', currency: 'TND', symbol: 'د.ت', rate: 3.12, timezone: 'Africa/Tunis' },
  { code: 'TR', name: 'Turkey', currency: 'TRY', symbol: '₺', rate: 32.2, timezone: 'Europe/Istanbul' },
  { code: 'TM', name: 'Turkmenistan', currency: 'TMT', symbol: 'T', rate: 3.50, timezone: 'Asia/Ashgabat' },
  { code: 'TV', name: 'Tuvalu', currency: 'AUD', symbol: 'A$', rate: 1.51, timezone: 'Pacific/Funafuti' },
  { code: 'UG', name: 'Uganda', currency: 'UGX', symbol: 'USh', rate: 3780.0, timezone: 'Africa/Kampala' },
  { code: 'UA', name: 'Ukraine', currency: 'UAH', symbol: '₴', rate: 40.2, timezone: 'Europe/Kyiv' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', symbol: 'د.إ', rate: 3.67, timezone: 'Asia/Dubai' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', symbol: '£', rate: 0.79, timezone: 'Europe/London' },
  { code: 'US', name: 'United States', currency: 'USD', symbol: '$', rate: 1.00, timezone: 'America/New_York' },
  { code: 'UY', name: 'Uruguay', currency: 'UYU', symbol: '$U', rate: 38.8, timezone: 'America/Montevideo' },
  { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', symbol: "so'm", rate: 12600.0, timezone: 'Asia/Tashkent' },
  { code: 'VU', name: 'Vanuatu', currency: 'VUV', symbol: 'VT', rate: 120.0, timezone: 'Pacific/Efate' },
  { code: 'VA', name: 'Vatican City', currency: 'EUR', symbol: '€', rate: 0.92, timezone: 'Europe/Vatican' },
  { code: 'VE', name: 'Venezuela', currency: 'VES', symbol: 'Bs.S', rate: 36.4, timezone: 'America/Caracas' },
  { code: 'VN', name: 'Vietnam', currency: 'VND', symbol: '₫', rate: 25400.0, timezone: 'Asia/Ho_Chi_Minh' },
  { code: 'YE', name: 'Yemen', currency: 'YER', symbol: '﷼', rate: 250.0, timezone: 'Asia/Aden' },
  { code: 'ZM', name: 'Zambia', currency: 'ZMW', symbol: 'ZK', rate: 26.5, timezone: 'Africa/Lusaka' },
  { code: 'ZW', name: 'Zimbabwe', currency: 'ZWG', symbol: 'ZiG', rate: 13.5, timezone: 'Africa/Harare' }
];
